server:
  port: 1920
  servlet:
    context-path: /employee

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cts_db
    username:  root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver